name: Publish to Server

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.3.1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
    
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install JavaScript dependencies
        run: yarn install

      - name: Compile CSS
        run: yarn tailwindcss build

      - name: Install Ruby dependencies
        run: bundle install

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rails test

  rubocop:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.3.1

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bundle install
      - name: Rubocop
        run: rubocop

  deploy:
    needs: [test, rubocop]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy changes
        run: |
          # Connect to the server via SSH and pull changes
          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_ADDRESS }} \
          'source $HOME/.asdf/asdf.sh && \
          cd ${{ secrets.APP_PATH }}  && \
          git pull origin main && \
          bundle install && \
          RAILS_ENV=production bundle exec rake assets:precompile && \
          sudo service nginx restart'