name: Ruby CI

on:
  push:
    branches:
      - '*'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.3.1

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bundle install
      - name: Rubocop
        run: rubocop