name: Ruby CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.3.1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
    
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install JavaScript dependencies
        run: yarn install

      - name: Compile CSS
        run: yarn tailwindcss build

      - name: Install Ruby dependencies
        run: bundle install

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rails test